name: building_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: null
  cached_network_image: null
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.0
  flutter_riverpod: null
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  flutterwave_standard: 1.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timezone: ^0.8.0
  transparent_image: ^2.0.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
