name: building_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: null
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.0
  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.3+2
  flutter_shimmer: ^2.1.2
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  timezone: ^0.8.0
  transparent_image: ^2.0.0
  

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
